-- Esegui questo script in Supabase SQL Editor.
-- Crea tabelle cloud separate dal DB locale SQLite.

create table if not exists public.app_pecore (
  tenant_id text not null,
  tag_id bigint not null,
  nome text not null,
  rfid text,
  note text,
  created_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (tenant_id, tag_id)
);

create table if not exists public.app_master (
  tenant_id text not null,
  tag_id bigint not null,
  nome text,
  rfid text,
  note text,
  created_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (tenant_id, tag_id)
);

create table if not exists public.app_storico (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  local_id bigint not null,
  tag_id bigint not null,
  master_id bigint,
  timestamp timestamptz not null,
  imported_at timestamptz,
  latitude double precision,
  longitude double precision,
  gps_valid integer,
  boot_count integer not null,
  battery_pct integer not null,
  battery_mv integer not null,
  temperature integer not null,
  rssi integer not null,
  updated_at timestamptz not null default now(),
  unique (tenant_id, local_id)
);

create table if not exists public.app_configurazione (
  tenant_id text not null,
  chiave text not null,
  valore text not null,
  updated_at timestamptz not null default now(),
  primary key (tenant_id, chiave)
);

-- RLS abilitata (consigliato). Per questa prima integrazione apriamo policy complete.
-- In produzione suggerisco auth utenti e policy per utente/tenant.
alter table public.app_pecore enable row level security;
alter table public.app_master enable row level security;
alter table public.app_storico enable row level security;
alter table public.app_configurazione enable row level security;

drop policy if exists app_pecore_all on public.app_pecore;
create policy app_pecore_all on public.app_pecore for all using (true) with check (true);

drop policy if exists app_master_all on public.app_master;
create policy app_master_all on public.app_master for all using (true) with check (true);

drop policy if exists app_storico_all on public.app_storico;
create policy app_storico_all on public.app_storico for all using (true) with check (true);

drop policy if exists app_configurazione_all on public.app_configurazione;
create policy app_configurazione_all on public.app_configurazione for all using (true) with check (true);
